Repository aguasdearuanda/zelio, pull requests merged in 2019-09, with the labels that each got.

#53 remove from student dashboard a box with counts
  app/views/student/dashboard/index.html.erb
Labels: enhancement

#57 Add recaptcha on Justification form
  Gemfile
  Gemfile.lock
  app/controllers/justifications_controller.rb
  app/controllers/student/justifications_controller.rb
  app/views/justifications/_form.html.erb
  app/views/student/justifications/_form.html.erb
  config/initializers/recaptcha.rb
Labels: Reviewed!

#70 [FIX] Modal is not getting the student id
  app/views/admin/klasses/_absences.html.erb
  app/views/admin/klasses/show.html.erb
Labels: Reviewed!, bug

#68 Small refactoring on Student model
  app/models/student.rb
Labels: in progress
